server:
  port: 8080

spring:
  application:
    name: Front-UI Service

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_ISSUER_HOST_AND_PORT:localhost:8082}/realms/master
        registration:
          front-ui:
            provider: keycloak
            authorizationGrantType: authorization_code
            client-id: front-ui
            client-secret:  ${FRONT_UI_KEYCLOAK_CLIENT_SECRET} #vbnIiLlecdM07flbEQTrP6JSthqrepAc
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email


logging:
  level:
    org.springframework.security: DEBUG

balance:
  service:
    url:  http://${ACCOUNTS_SERVICE_HOST}:8081
