server:
  port: ${GATEWAY_PORT}
spring:
  application:
    name: api-gateway
  #security:
  #  oauth2:
  #    client:
  #      provider:
  #        keycloak:
  #          issuer-uri: http://${KEYCLOAK_ISSUER_HOST_AND_PORT:localhost:8082}/realms/master
  #      registration:
  #        gateway-api:
  #          provider: keycloak
  #          #authorizationGrantType: authorization_code
  #          client-id: gateway-api
  #          client-secret: ${GATEWAY_API_KEYCLOAK_CLIENT_SECRET}
            #redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #scope: openid, profile, email
  cloud:
    discovery:
      client:
        simple:
          instances:
            accounts-service: # ?? ?? ?????????? Service Discovery, ??????? ?????????? ????? ??????????????
              - uri: http://127.0.0.1:${ACCOUNTS_PORT} #???? ????????? ??, ??? ??? ?????? ???? ???? (??? ?????) ???????? accounts service
    gateway:
      routes:
        - id: accounts-route  # ID ?????
          uri: lb://accounts-service  # URI ????????????, ?? ??????? ??????? ?????????????? ??????
          predicates:
            - Path=/accounts/** # URI ???????????? ? Gateway ???????, ? ??????? ???????? ????
          filters:
          #  - RewritePath=/accounts/?(?<segment>.*), /$\{segment} # ??????, ??????? ???????????? ?????? ? ???????? ??????? (????????? ??? ??????? ? ??????)
            - TokenRelay= # ??? ???????? ??????
logging:
  level:
    root: INFO
    reactor.netty: DEBUG
    org:
      springframework:
        security: DEBUG
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG
