spring:
  application:
    name: cash

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak.issuer-uri}
        registration:
          cash:
            provider: keycloak
            authorizationGrantType: authorization_code
            client-id: cash
            client-secret: ${cash.client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email

  config.import: "consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        service-name: cash
        ip-address: ${app.ip-address}
        prefer-ip-address: true
      config:
        enabled: true
        prefix: config
        defaultContext: application
        format: YAML
