spring:
  application:
    name: accounts-service

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver

    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}

  config.import: "consul:"
  cloud:
    consul:
      host: ${CONSUL_HOST}         # ????? Consul (?? ????????? localhost)
      port: ${CONSUL_PORT}         # ???? Consul (8500 ?? ?????????)
      discovery:
        service-name: accounts-service  # ?????????????, ?? ????????? ??????? spring.application.name
        ip-address: ${app.ip-address}
        prefer-ip-address: true
      config:
        enabled: true            # ???????? Consul Config ??? ??????? ????????????
        prefix: config           # ??????? ? KV-????????? Consul (?? ????????? "config")
        defaultContext: application  # ???????? ?? ?????????
        format: YAML
